---
name: RDF-AllegroGraph-Easy
version: 0.03
author:
  - 'Robert Barta <rho@devc.at>'
abstract: Simplistic Interface to AllegroGraph HTTP server
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  JSON: 0
  LWP: 0
  Regexp::Common: 0
  Test::Exception: 0
  Test::More: 0
  Test::Pod::Coverage: 0
  URI::Escape: 0
configure_requires:
  Module::Build: 0.340201
provides:
  LWP::UserAgent::AG:
    file: lib/RDF/AllegroGraph/Server.pm
  RDF::AllegroGraph:
    file: lib/RDF/AllegroGraph.pm
    version: 0.03
  RDF::AllegroGraph::Catalog:
    file: lib/RDF/AllegroGraph/Catalog.pm
    version: 0.03
  RDF::AllegroGraph::Easy:
    file: lib/RDF/AllegroGraph/Easy.pm
    version: 0.03
  RDF::AllegroGraph::Repository:
    file: lib/RDF/AllegroGraph/Repository.pm
    version: 0.03
  RDF::AllegroGraph::Server:
    file: lib/RDF/AllegroGraph/Server.pm
    version: 0.02
  RDF::AllegroGraph::Utils:
    file: lib/RDF/AllegroGraph/Utils.pm
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
