--- #YAML:1.0
name:                RDF-AllegroGraph-Easy
version:             0.01
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    JSON:                          0
    LWP:                           0
    Regexp::Common:                0
    Test::Exception:               0
    Test::More:                    0
    Test::Pod::Coverage:           0
    URI::Escape:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
